masev_settings_api_schema:
    path:     /masev_settings/api/schema
    defaults: { _controller: MasevSettingsBundle:Api:schema }

masev_settings_api_data:
    path:     /masev_settings/api/data
    defaults: { _controller: MasevSettingsBundle:Api:data }

masev_settings_api_sections:
    path:     /masev_settings/api/sections
    defaults: { _controller: MasevSettingsBundle:Api:sections }

masev_settings_api_update:
    path:     /masev_settings/api/update
    defaults: { _controller: MasevSettingsBundle:Api:update }